# Generated by Django 4.2 on 2024-08-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='stuck',
            field=models.BigIntegerField(),
        ),
    ]
