# Generated by Django 4.2 on 2024-08-08 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_stuck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='owener',
            new_name='owner',
        ),
    ]
