# Generated by Django 4.2 on 2024-08-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='national_id',
            field=models.CharField(max_length=10),
        ),
    ]
