# Generated by Django 4.2 on 2024-08-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_people_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='national_id',
            field=models.BigIntegerField(),
        ),
    ]
