# Generated by Django 4.2 on 2024-08-12 07:55

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_people_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='national_id',
            field=models.BigIntegerField(validators=[people.models.validator_length]),
        ),
    ]
